export const platforms=['京东','淘宝','拼多多','苏宁','南粤分享汇','史泰博'] as const;
export type Platform=typeof platforms[number];
export type Match='pending'|'exact'|'mismatch'|'notfound';
export type Strategy='min'|'median'|'max';
export type ClientName='通用'|'示例客户A'|'示例客户B'|'示例客户C';
export interface Evidence{id:string;name:string;url:string;kind?:'origin'|'aggregate'|'input';capturedAt?:string;sourceUrl?:string}
export const checkNames={brand:'品牌',model:'型号 / 条码',spec:'规格参数',color:'颜色',pack:'包装数量',version:'版本 / 原装或兼容'};
export interface Quote{id:string;platform:Platform;store:string;title:string;spec:string;url:string;price:number|null;match:Match;conditions:string;checkedAt:string;evidence:Evidence[];targetSignature:string;sourceKind?:'search'|'detail'|'aggregate'|'manual';collectedAt?:string;sourceUpdatedAt?:string;priceVerifiedAt?:string;originUrl?:string;checks?:Partial<Record<keyof typeof checkNames,boolean>>;availability?:'unknown'|'available'|'unavailable';priceBasis?:'listed'|'coupon'|'member';conditionsConfirmed?:boolean;sourceText?:string}
export interface Task{id:string;name:string;brand:string;model:string;spec:string;color:string;pack:string;description:string;photo:Evidence|null;specConfirmed:boolean;quotes:Quote[];strategy:Strategy;updatedAt:string;revision:number;unit?:string;quantity?:number;version?:string;client?:ClientName;requiredPlatforms?:Platform[];sampleSize?:number;minimumSamples?:number;priceBasis?:'listed'|'coupon'|'member'}
export const matchNames:Record<Match,string>={pending:'待核验',exact:'已核实同款',mismatch:'规格不符',notfound:'未找到'};
export const strategyNames:Record<Strategy,string>={min:'最低样本价',median:'中位样本价',max:'最高样本价'};
export function blankTask():Task{return {id:crypto.randomUUID(),name:'',brand:'',model:'',spec:'',color:'',pack:'1件',unit:'件',quantity:1,version:'',client:'通用',requiredPlatforms:['京东','淘宝','拼多多'],sampleSize:5,minimumSamples:1,priceBasis:'listed',description:'',photo:null,specConfirmed:false,quotes:[],strategy:'min',updatedAt:new Date().toISOString(),revision:0};}
export function normalizeTask(t:Task):Task{return {...t,unit:t.unit??'件',quantity:t.quantity??1,version:t.version??'',client:t.client??'通用',requiredPlatforms:t.requiredPlatforms??['京东','淘宝','拼多多'],sampleSize:t.sampleSize??5,minimumSamples:t.minimumSamples??1,priceBasis:t.priceBasis??'listed',quotes:t.quotes.map(q=>q.match==='exact'&&effectiveMatch(q,t)!=='exact'?{...q,match:'pending'}:q)};}
export function taskPlatforms(t:Task):Platform[]{return t.requiredPlatforms??['京东','淘宝','拼多多'];}
export function signature(t:Task){return JSON.stringify([t.name,t.brand,t.model,t.spec,t.color,t.pack,t.version??'',t.unit??'件',String(t.quantity??1)].map(s=>s.trim().toLowerCase()));}
export function safeUrl(s:string){try{const u=new URL(s);return ['https:','http:'].includes(u.protocol)?u.href:'';}catch{return '';}}
export function productKey(value:string){try{const u=new URL(value),dp=u.searchParams.get('dp_id')||u.pathname.match(/\/crc64\/dp(.+)$/)?.[1];if(dp&&/(^|\.)gwdang\.com$/.test(u.hostname)){const m=dp.match(/^(.+)-(3|83|370|25|813|291)$/);if(m)return `${({'3':'京东','83':'淘宝','370':'拼多多','25':'苏宁','813':'南粤分享汇','291':'史泰博'} as Record<string,string>)[m[2]]}:${m[1]}`;return 'gwdang:'+dp;}const h=u.hostname;if(/(^|\.)jd\.com$/.test(h))return '京东:'+(u.pathname.match(/\/(\d+)\.html/)?.[1]||u.pathname);if(/(^|\.)(taobao|tmall)\.com$/.test(h))return '淘宝:'+(u.searchParams.get('id')||u.pathname);if(/(^|\.)yangkeduo\.com$/.test(h))return '拼多多:'+(u.searchParams.get('goods_id')||u.pathname);if(/(^|\.)suning\.com$/.test(h)){const id=u.pathname.match(/\/(\d+)\.html/)?.[1];return '苏宁:'+(id?id.replace(/^0+(?=\d)/,''):u.pathname);}return h+u.pathname+'?'+(u.searchParams.get('id')||u.searchParams.get('goods_id')||'');}catch{return '';}}
export function originMatches(q:Quote){try{const u=new URL(q.originUrl||q.url);if(!['http:','https:'].includes(u.protocol)||u.username||u.password)return false;const d:Record<Platform,RegExp>={'京东':/(^|\.)jd\.com$/,'淘宝':/(^|\.)(taobao|tmall)\.com$/,'拼多多':/(^|\.)yangkeduo\.com$/,'苏宁':/(^|\.)suning\.com$/,'南粤分享汇':/a^/,'史泰博':/(^|\.)staples\.cn$/};if(!d[q.platform].test(u.hostname))return false;const key=productKey(q.url),origin=productKey(u.href);if(['京东','淘宝','拼多多','苏宁'].includes(q.platform))return new RegExp('^'+q.platform+':\\d+$').test(origin)&&(!key.startsWith(q.platform+':')||key===origin);return !key.startsWith(q.platform+':');}catch{return false;}}
export function effectiveMatch(q:Quote,t:Task):Match{return q.match==='exact'&&(!t.specConfirmed||q.targetSignature!==signature(t)||!Object.keys(checkNames).every(k=>q.checks?.[k as keyof typeof checkNames]))?'pending':q.match;}
const TEN_MINUTES=600000;
export function freshness(q:Quote,now=Date.now()):'fresh'|'stale'|'unknown'{const value=q.priceVerifiedAt&&originMatches(q)?q.priceVerifiedAt:q.sourceUpdatedAt;if(!value)return 'unknown';const age=now-Date.parse(value);return Number.isFinite(age)&&age>=0?(age<=TEN_MINUTES?'fresh':'stale'):'unknown';}
export const freshnessNames={fresh:'10分钟内价格依据',stale:'价格已超过10分钟',unknown:'来源价格时效未知'};
export function eligible(t:Task,p:Platform,now=Date.now()){const stores=new Set<string>(),urls=new Set<string>();return t.quotes.filter(q=>{if(q.platform!==p||effectiveMatch(q,t)!=='exact'||freshness(q,now)!=='fresh'||q.availability!=='available'||!q.conditionsConfirmed||(q.priceBasis??'listed')!==(t.priceBasis??'listed')||typeof q.price!=='number'||!Number.isFinite(q.price)||q.price<=0||!safeUrl(q.url))return false;const store=q.store.replace(/\s/g,'').toLowerCase(),key=productKey(q.url);if(!store||platforms.some(p=>p.toLowerCase()===store)||stores.has(store)||urls.has(key))return false;stores.add(store);urls.add(key);return true;}).slice(0,t.sampleSize??5).sort((a,b)=>a.price!-b.price!||a.id.localeCompare(b.id));}
export function statistics(t:Task,p:Platform,now=Date.now()){const a=eligible(t,p,now),n=a.length;return {count:n,min:n?a[0].price:null,max:n?a[n-1].price:null,median:n?Math.round((a[Math.floor((n-1)/2)].price!+a[Math.floor(n/2)].price!)*50)/100:null};}
export function selection(t:Task,p:Platform,now=Date.now()){const a=eligible(t,p,now),n=a.length;if(n<(t.minimumSamples??1))return null;const quotes=t.strategy==='min'?[a[0]]:t.strategy==='max'?[a[n-1]]:n%2?[a[Math.floor(n/2)]]:[a[n/2-1],a[n/2]];return {price:Math.round(quotes.reduce((s,q)=>s+q.price!,0)/quotes.length*100)/100,quotes,synthetic:quotes.length>1};}
export function selected(t:Task,p:Platform){const s=selection(t,p);return s&&!s.synthetic?s.quotes[0]:null;}
export function platformStatus(t:Task,p:Platform,now=Date.now()){const n=eligible(t,p,now).length;if(n>=(t.minimumSamples??1))return n===1?'仅1家有效样本，无法区分高中低':`${n}家有效样本`;if(n)return `有效样本不足${t.minimumSamples}家（已有${n}家）`;const a=t.quotes.filter(q=>q.platform===p);return a.some(q=>effectiveMatch(q,t)==='exact')?'待补价格时效、库存或价格条件':a.some(q=>q.match==='pending')?'待核验':a.some(q=>q.match==='notfound')?'未找到':a.length?'无匹配报价':'待检索';}
export function evidenceReady(q:Quote,now=Date.now()){return q.evidence.some(e=>e.kind==='origin'&&!!e.sourceUrl&&productKey(e.sourceUrl)===productKey(q.originUrl||q.url)&&e.capturedAt&&now-Date.parse(e.capturedAt)>=0&&now-Date.parse(e.capturedAt)<=TEN_MINUTES);}
export function deliveryIssues(t:Task,now=Date.now()){const reasons:string[]=[];if(!t.specConfirmed)reasons.push('目标规格未确认');for(const p of taskPlatforms(t)){const s=selection(t,p,now);if(!s){reasons.push(p+'：'+platformStatus(t,p,now));continue;}if(s.synthetic)reasons.push(p+'：中位数为计算值，需选择实际店铺报价后交付');for(const q of s.quotes)if(!evidenceReady(q,now)||!originMatches(q)||!q.priceVerifiedAt)reasons.push(p+'：缺少10分钟内的来源商城核验、截图或直达链接');}if(t.client==='示例客户B'||t.client==='示例客户C')reasons.push(t.client+'：正式客户模板尚未提供');return [...new Set(reasons)];}
export function sampleRule(t:Task){return `每平台按录入顺序取前${t.sampleSize??5}家合格店铺，至少${t.minimumSamples??1}家即可统计；偶数样本中位数取中间两价平均值，计算值不代表店铺报价。仅统计同口径、已核实且价格依据在10分钟内的样本。`;}
export function searchUrl(p:Platform,t:Task){const q=encodeURIComponent([t.brand,t.name,t.model,t.spec,t.color,t.pack,t.version].filter(Boolean).join(' '));return p==='京东'?`https://search.jd.com/Search?keyword=${q}`:p==='淘宝'?`https://s.taobao.com/search?q=${q}`:p==='拼多多'?`https://mobile.yangkeduo.com/search_result.html?search_key=${q}`:p==='苏宁'?`https://search.suning.com/${q}/`:`https://www.gwdang.com/search?keyword=${q}`;}
function text(v:unknown,max=2000){if(typeof v!=='string'||v.length>max)throw Error('字段格式或长度不符合要求');}
export function validateTask(v:unknown):Task{
 if(!v||typeof v!=='object')throw Error('任务格式不正确');const t=v as Task;
 if(!/^[a-f0-9-]{36}$/.test(t.id))throw Error('任务编号无效');for(const k of ['name','brand','model','spec','color','pack','description'] as const)text(t[k]);if(!t.name.trim())throw Error('请填写商品名称');
 if(!['min','median','max'].includes(t.strategy)||typeof t.specConfirmed!=='boolean'||!Number.isSafeInteger(t.revision)||t.revision<0)throw Error('任务状态无效');
 if(!Array.isArray(t.quotes)||t.quotes.length>500)throw Error('每项任务最多500条报价');
 const n={...t,unit:t.unit??'件',quantity:t.quantity??1,version:t.version??'',client:t.client??'通用',requiredPlatforms:t.requiredPlatforms??['京东','淘宝','拼多多'],sampleSize:t.sampleSize??5,minimumSamples:t.minimumSamples??1,priceBasis:t.priceBasis??'listed'};
 text(n.unit,100);text(n.version,200);if(!n.unit.trim()||!Number.isFinite(n.quantity)||n.quantity<=0||n.quantity>1000000)throw Error('采购单位和数量无效');
 if(!['通用','示例客户A','示例客户B','示例客户C'].includes(n.client))throw Error('客户无效');
 if(!Array.isArray(n.requiredPlatforms)||!n.requiredPlatforms.length||n.requiredPlatforms.length>6||new Set(n.requiredPlatforms).size!==n.requiredPlatforms.length||n.requiredPlatforms.some(p=>!platforms.includes(p as Platform)))throw Error('至少选择一个有效平台');
 if(!Number.isInteger(n.sampleSize)||n.sampleSize<1||n.sampleSize>5||!Number.isInteger(n.minimumSamples)||n.minimumSamples<1||n.minimumSamples>n.sampleSize)throw Error('样本范围须为1至5家，最低数量不能超过上限');
 if(!['listed','coupon','member'].includes(n.priceBasis))throw Error('价格口径无效');
 if(t.specConfirmed&&(!t.spec.trim()||!t.brand.trim()||!t.pack.trim()))throw Error('确认规格前请填写品牌、规格与包装数量');
 const ids=new Set<string>();for(const q of t.quotes){if(!q||!/^[a-f0-9-]{36}$/.test(q.id)||ids.has(q.id))throw Error('报价编号重复或无效');ids.add(q.id);if(!platforms.includes(q.platform)||!Object.hasOwn(matchNames,q.match))throw Error('平台或匹配状态不正确');for(const k of ['store','title','spec','url','conditions','targetSignature'] as const)text(q[k],4000);
 if(q.url&&!safeUrl(q.url)||q.originUrl&&!safeUrl(q.originUrl))throw Error('商品链接必须是http或https链接');if(q.price!==null&&(typeof q.price!=='number'||!Number.isFinite(q.price)||q.price<=0||q.price>100000000))throw Error('价格必须是大于0的有效金额');
 if(!Number.isFinite(Date.parse(q.checkedAt)))throw Error('核验时间无效');for(const value of [q.collectedAt,q.sourceUpdatedAt,q.priceVerifiedAt].filter(Boolean))if(!Number.isFinite(Date.parse(value!)))throw Error('时间无效');
 if(q.availability&&!['unknown','available','unavailable'].includes(q.availability)||q.priceBasis&&!['listed','coupon','member'].includes(q.priceBasis)||q.sourceKind&&!['manual','aggregate','search','detail'].includes(q.sourceKind))throw Error('报价状态无效');
 if(q.conditionsConfirmed!==undefined&&typeof q.conditionsConfirmed!=='boolean')throw Error('价格条件确认必须为布尔值');
 if(q.checks&&Object.entries(q.checks).some(([k,v])=>!Object.hasOwn(checkNames,k)||typeof v!=='boolean'))throw Error('核验项无效');
 if(q.match==='exact'&&(!q.store.trim()||!q.spec.trim()||q.price===null||!q.url||effectiveMatch(q,t)!=='exact'))throw Error('请确认目标规格，并逐项核实品牌、型号、参数、颜色、包装和版本');validateEvidence(q.evidence);}
 if(t.photo)validateEvidence([t.photo]);return n as Task;
}
function validateEvidence(a:Evidence[]){if(!Array.isArray(a)||a.length>10)throw Error('每条报价最多10张凭证');for(const e of a){if(!e||!/^[a-f0-9-]{36}$/.test(e.id)||e.url!==`/api/files/${e.id}`)throw Error('凭证编号无效');text(e.name,200);if(e.kind&&!['origin','aggregate','input'].includes(e.kind))throw Error('凭证来源无效');if(e.sourceUrl&&!safeUrl(e.sourceUrl))throw Error('凭证商品链接无效');if(e.capturedAt&&!Number.isFinite(Date.parse(e.capturedAt)))throw Error('凭证时间无效');}}
