const $=s=>document.querySelector(s);let state=null,results={},busy=false;let projectMap={},activeProject=null,projectDirty=true;const selectedRows=new Set();
const fields={name:'品名',spec:'规格',unit:'单位',quantity:'数量'};
const aliases={name:['品名','商品名称','食材名称','物料名称','名称'],spec:['规格','规格型号'],unit:['单位','计量单位'],quantity:['数量','采购数量','订购数量']};
function el(tag,text){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e}
function msg(t){$('#message').textContent=t}
async function api(path,data){const r=await fetch('/api/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:state?.id,...data})});if(!r.ok)throw Error((await r.json()).error);return path==='export'?r.blob():r.json()}
function mapping(){return Object.fromEntries(Object.keys(fields).map(k=>[k,Number($('#map-'+k).value)]))}
function locked(v){busy=v;document.querySelectorAll('button,input,select').forEach(e=>e.disabled=v);$('#date').disabled=v||$('#mode').value!=='day';$('#query').disabled=v||!state;$('#export').disabled=v||!state||projectDirty;$('#print').disabled=v||!state||projectDirty;$('#query').disabled=v||!state||projectDirty;document.querySelectorAll('.print-row').forEach(c=>c.disabled=v||!results[c.closest('tr').dataset.row]?.confirmed);}
function configure(d){state=d;results={};selectedRows.clear();$('#config').hidden=false;$('#sheet').replaceChildren(...d.sheets.map(s=>{const o=el('option',s);o.value=s;return o}));$('#sheet').value=d.sheet;$('#header').value=d.header;$('#mapping').replaceChildren();for(const [k,label] of Object.entries(fields)){const l=el('label',label+'列');const sel=el('select');sel.id='map-'+k;const empty=el('option','未指定');empty.value=-1;sel.append(empty);d.headers.forEach((h,i)=>{const o=el('option',`${i+1} · ${h||'空表头'}`);o.value=i;sel.append(o)});sel.value=d.headers.findIndex(h=>aliases[k].includes(h.trim()));sel.onchange=invalidate;l.append(sel);$('#mapping').append(l)}locked(false);render()}
function render(){const m=mapping();$('#rows').replaceChildren();state.rows.forEach((vals,i)=>{const row=state.header+i+1,r=results[row],tr=el('tr');tr.dataset.row=row;const pick=el('td');const check=el('input');check.type='checkbox';check.className='print-row';check.disabled=!r?.confirmed;check.checked=selectedRows.has(row);check.onchange=()=>{if(check.checked)selectedRows.add(row);else selectedRows.delete(row)};pick.append(check,document.createTextNode(' '+row));tr.append(pick);const name=el('td',vals[m.name]??'—');name.append(el('small',vals[m.spec]??''));tr.append(name);tr.append(el('td',`${vals[m.unit]??'—'} / ${vals[m.quantity]??'—'}`));const choice=el('td');if(r?.items?.length){const select=el('select');select.setAttribute('aria-label',`第${row}行候选`);const opt=el('option','请选择并核对候选');opt.value=-1;select.append(opt);r.items.forEach((c,j)=>{const o=el('option',`${c.name} · ${c.spec||'无规格'} · ${c.origin||'无产地'} · ${c.average_price??'缺价'}元/${c.unit||'未知单位'} · ${c.published_at.slice(0,10)}`);o.value=j;select.append(o)});select.value=r.selected??-1;const detail=el('small','最低 / 平均 / 最高价会随候选展示；选中后需点确认。');const btn=el('button','确认匹配并填价');const factor=el('input');factor.type='number';factor.min='0.000001';factor.step='any';factor.placeholder='换算比例';factor.value=r.factor??'';factor.setAttribute('aria-label',`第${row}行单位换算比例`);const fee=el('input');fee.type='number';fee.step='any';fee.value=r.fee??activeProject?.fee??0;fee.setAttribute('aria-label',`第${row}行加工费`);const adj=el('input');adj.type='number';adj.step='any';adj.value=r.adjustment??activeProject?.adjustment??0;adj.setAttribute('aria-label',`第${row}行浮动`);const note=el('small');const clear=el('button','撤销确认');clear.className='secondary';clear.disabled=r.selected===undefined;
const same=(a,b)=>{const n=x=>({'公斤':'kg','千克':'kg','KG':'kg','市斤':'斤','克':'g'}[x]||x);return !!a&&!!b&&n(a)===n(b)};
function update(){const c=r.items[Number(select.value)];if(!c){btn.disabled=true;factor.hidden=true;note.textContent='';return}btn.disabled=false;detail.textContent=`最低 ${c.low_price??'—'} / 平均 ${c.average_price??'—'} / 最高 ${c.high_price??'—'} 元/${c.unit||'未知'}；实际日期 ${c.published_at.slice(0,10)}`;const ok=same(r.unit,c.unit);factor.hidden=ok;note.textContent=ok?'单位一致，按已保存项目基准和规则计算。':`单位不同或缺失：原单位「${r.unit||'未提供'}」，行情「${c.unit||'未提供'}」。请输入 1 个原单位等于多少行情单位（例如 1 公斤 = 2 斤，填 2）。不确定请勿确认。`}
let pendingClear=Promise.resolve();function markEdited(){if(!r.confirmed)return;delete r.confirmed;delete r.price;delete r.price_decimal;selectedRows.delete(row);check.checked=false;check.disabled=true;tr.children[4].textContent='—';tr.children[5].textContent='已修改，请重新确认';document.querySelector('#print-frame')?.remove();pendingClear=api('clear',{row}).catch(e=>{msg(e.message);throw e});}select.onchange=()=>{factor.value='';markEdited();update()};factor.oninput=fee.oninput=adj.oninput=markEdited;btn.onclick=async()=>{try{await pendingClear;const c=r.items[Number(select.value)];results[row]=await api('confirm',{row,index:Number(select.value),factor:same(r.unit,c.unit)?1:factor.value,fee:fee.value,adjustment:adj.value});render()}catch(e){msg(e.message)}};clear.onclick=async()=>{try{await pendingClear;selectedRows.delete(row);document.querySelector('#print-frame')?.remove();results[row]=await api('clear',{row});render()}catch(e){msg(e.message)}};const feeLabel=el('label','本行加工费 / 原单单位');feeLabel.append(fee);const adjLabel=el('label',activeProject?.adjustment_kind==='rate'?'本行增减率（-0.05 = 下浮5%）':'本行乘数（0.95 = 下浮5%）');adjLabel.append(adj);choice.append(select,detail,note,factor,feeLabel,adjLabel,btn,clear);update()}else choice.textContent='—';tr.append(choice,el('td',r?.price!==undefined?String(r.price):r?.protected?String(r.original_price):'—'),el('td',(r?.status||'未查询')+(r?.formula?'；'+r.formula:'')));$('#rows').append(tr)});$('#summary').textContent=`原表 ${state.rows.length} 行 · 已确认 ${Object.values(results).filter(r=>r.price!==undefined).length} 行`}
$('#file').onchange=async()=>{if(!$('#file').files[0])return;locked(true);try{const r=await fetch('/api/upload',{method:'POST',body:$('#file').files[0]});const d=await r.json();if(!r.ok)throw Error(d.error);configure(d);msg('已上传。请核对工作表、表头行和列映射，再批量查价。')}catch(e){msg(e.message)}finally{locked(false)}};
$('#preview').onclick=async()=>{try{configure({...await api('preview',{sheet:$('#sheet').value,header:Number($('#header').value)}),id:state.id});msg('预览已更新，旧查询已清空。')}catch(e){msg(e.message)}};
function invalidate(){document.querySelector('#print-frame')?.remove();results={};selectedRows.clear();if(state)render();msg('设置已变更，请重新批量查价。');$('#export').disabled=true;$('#print').disabled=true}
$('#mode').onchange=()=>{$('#date').disabled=$('#mode').value!=='day';invalidate()};$('#date').onchange=invalidate;$('#sheet').onchange=()=>{$('#query').disabled=true;$('#export').disabled=true;msg('请点击重新预览以应用工作表。')};$('#header').oninput=()=>{$('#query').disabled=true;$('#export').disabled=true;msg('请点击重新预览以应用表头行。')};
$('#date').value=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
$('#query').onclick=async()=>{locked(true);try{await api('setup',{project_id:activeProject?.id,mapping:mapping(),date:$('#mode').value==='latest'?'latest':$('#date').value});results={};selectedRows.clear();for(let i=0;i<state.rows.length;i++){const row=state.header+i+1;msg(`正在查询 ${i+1} / ${state.rows.length} 行，请勿关闭页面…`);results[row]=await api('query',{row})}render();msg('查询完成。请逐行选择候选并确认；未确认行导出时价格留空。')}catch(e){msg(e.message)}finally{locked(false)}};
$('#export').onclick=async()=>{try{const blob=await api('export',{}),url=URL.createObjectURL(blob),a=el('a');a.href=url;a.download='新发地批量查价结果-有价格.xlsx';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);msg('已导出：新发地批量查价结果-有价格.xlsx。未确认或查询失败行的参考价格留空。')}catch(e){msg(e.message)}};

const ruleInputs=['project-name','purpose','basis','adjustment-kind','adjustment','fee','fee-order','rounding','fixed-price'];
function fillProject(r){activeProject=r||null;projectDirty=!r;const defaults={name:'',purpose:'sales',basis:'average_price',adjustment_kind:'rate',adjustment:'0',fee:'0',fee_order:'before',rounding:'ROUND',fixed_price:'0'};for(const id of ruleInputs){const key=id==='project-name'?'name':id.replaceAll('-','_');$('#'+id).value=(r||defaults)[key]}invalidate();locked(false);$('#project-status').textContent=r?`已载入 ${r.name} · 版本 ${r.version}；重新查询后应用。`:'请填写并保存新项目。'}
async function loadProjects(id){const response=await fetch('/api/projects');if(!response.ok)throw Error('项目读取失败');projectMap=await response.json();$('#project').replaceChildren();const empty=el('option','新建项目');empty.value='';$('#project').append(empty);Object.values(projectMap).forEach(p=>{const o=el('option',p.name+' · '+(p.purpose==='sales'?'销售':'采购'));o.value=p.id;$('#project').append(o)});$('#project').value=id||'';if(id)fillProject(projectMap[id])}
$('#project').onchange=()=>fillProject(projectMap[$('#project').value]);
ruleInputs.forEach(id=>$('#'+id).oninput=()=>{projectDirty=true;invalidate();locked(false);$('#project-status').textContent='规则已修改，请保存后重新查询；旧确认结果已清空。'});
$('#save-project').onclick=async()=>{try{const project=Object.fromEntries(ruleInputs.map(id=>[id==='project-name'?'name':id.replaceAll('-','_'),$('#'+id).value]));if(activeProject)project.id=activeProject.id;const saved=await api('projects',{project});await loadProjects(saved.id);msg('项目规则已保存，下次打开后可直接选择复用。')}catch(e){msg(e.message)}};
$('#print').onclick=async()=>{try{if(projectDirty)throw Error('请先保存规则并重新查询');const d=await api('print',{rows:[...selectedRows]});const old=document.querySelector('#print-frame');if(old)old.remove();const iframe=el('iframe');iframe.id='print-frame';iframe.title='A4价格核对凭证';iframe.style='width:100%;height:700px;border:1px solid #ccd6ce';iframe.srcdoc=d.html;document.querySelector('main').append(iframe);iframe.scrollIntoView({behavior:'smooth'});msg('已生成A4凭证预览；点击预览中的打印，可保存为PDF。此页是生成汇总，不是网站截图。')}catch(e){msg(e.message)}};
loadProjects().catch(e=>msg(e.message));
