import fs from 'node:fs';import path from 'node:path';import {randomUUID,createHash} from 'node:crypto';import {chromium} from 'playwright';
import {searchUrl,searchPlan,filterCandidates,queryFromUrl,platformCoverage} from './search-match.mjs';
const HOME='https://www.gwdang.com/';
export function extractNextPage(){return [...document.querySelectorAll('a[href]')].find(a=>a.getBoundingClientRect().width>0&&(a.rel==='next'||/^(?:下一页|下页|下一頁)\s*[>›»]?\s*$/.test(a.textContent.trim())))?.href||null;}
export function validNextPage(next,current){if(typeof next!=='string')return null;const allowed=allowedAggregateUrl(next);if(!allowed)return null;const a=new URL(allowed),b=new URL(current);return a.pathname==='/search'&&b.pathname==='/search'&&a.href!==b.href&&queryFromUrl(a.href)&&queryFromUrl(a.href)===queryFromUrl(b.href)?a.href:null;}
export function allowedAggregateUrl(value){try{const u=new URL(value);return u.protocol==='https:'&&u.hostname==='www.gwdang.com'&&!u.username&&!u.password&&(/^\/crc64\/dp-?\d+-\d+$/.test(u.pathname)||u.pathname==='/search')?u.href:'';}catch{return '';}}
export function extractAggregate(){
 const visible=e=>!!e&&e.getBoundingClientRect().width>0&&e.getBoundingClientRect().height>0;
 const detail=[...document.querySelectorAll('a[href*="/product/get_trans?"]')].filter(a=>a.textContent.trim().length>12&&visible(a));
 const roots=detail.length?detail.map(a=>{let el=a.parentElement;for(let i=0;i<5&&el&&!/[¥￥]/.test(el.innerText);i++)el=el.parentElement;return {a,el};}):[...document.querySelectorAll('li')].filter(el=>visible(el)&&el.querySelector('a[href^="/crc64/dp"]')).map(el=>({el,a:[...el.querySelectorAll('a[href^="/crc64/dp"]')].find(a=>a.textContent.trim())}));
 return roots.slice(0,500).filter(x=>x.a&&x.el).map(({a,el},index)=>{el.setAttribute('data-gq-aggregate',String(index));return {index,title:a.textContent.trim(),url:a.href,text:el.innerText,labels:[...el.querySelectorAll('[title]')].map(e=>e.title)};});
}
export function aggregateQuotes(rows,at){const platforms={'3':'京东','83':'淘宝','370':'拼多多','25':'苏宁','813':'南粤分享汇','291':'史泰博'},seen=new Set();return rows.flatMap(row=>{let u,id;try{u=new URL(row.url);id=u.searchParams.get('dp_id')||u.pathname.match(/\/crc64\/dp(.+)$/)?.[1];}catch{return [];}const match=id?.match(/^(-?\d+)-(\d+)$/),platform=match&&platforms[match[2]];if(!platform||seen.has(id))return [];seen.add(id);const prices=[...row.text.matchAll(/[¥￥]\s*([\d,.]+)/g)].map(m=>Number(m[1].replaceAll(',','')));const listedAfterCoupon=prices.length===2&&/[¥￥]\s*[\d,.]+\s*券后价\s*[¥￥]/.test(row.text);const listedBeforeFinal=prices.length===2&&/[¥￥]\s*[\d,.]+\s*[¥￥]\s*[\d,.]+\s*到手价/.test(row.text);const price=prices.length===1?prices[0]:listedAfterCoupon?prices[1]:listedBeforeFinal?prices[0]:null;const lines=row.text.split('\n').map(x=>x.trim()).filter(Boolean);const shop=row.labels?.filter(x=>x!==row.title&&!/价格保护|元券/.test(x)).at(-1)||lines.findLast(x=>/店|专区|分享汇|史泰博/.test(x))||'';
 const originUrl=match[2]==='3'?`https://item.jd.com/${match[1]}.html`:match[2]==='83'?`https://detail.tmall.com/item.htm?id=${match[1]}`:match[2]==='370'?`https://mobile.yangkeduo.com/goods.html?goods_id=${match[1]}`:'';
 return [{id:randomUUID(),platform,store:shop,title:row.title.slice(0,1000),spec:'',url:row.url,originUrl,price:price>0?price:null,match:'pending',conditions:price!==null?'聚合标价（不取券后价）；选中SKU、优惠、运费、税费及来源时效待核验。':'页面存在多个价格或未取得单一价格，请核对价格口径后录入。',checkedAt:at,collectedAt:at,evidence:[],targetSignature:'',sourceKind:'aggregate',sourceText:row.text.slice(0,2500),availability:/缺货中|下架/.test(row.text)?'unavailable':'unknown',priceBasis:'listed',aggregateIndex:row.index,aggregateProductId:id}];});}
export class Aggregator{
 constructor({root,saveImage,launchContext,clock=()=>Date.now()}){this.root=root;this.saveImage=saveImage;this.launchContext=launchContext;this.clock=clock;this.busy=false;this.blocked=false;this.nextNavigationAt=0;this.last=null;this.metrics={startedAt:null,endedAt:null,requests:0,cacheHits:0,verificationEvents:0,manualResumes:0};this.cacheDir=path.join(root,'aggregate-cache');fs.mkdirSync(this.cacheDir,{recursive:true});this.stateFile=path.join(root,'aggregate-state.json');try{const saved=JSON.parse(fs.readFileSync(this.stateFile,'utf8'));this.metrics={...this.metrics,...saved.metrics};this.blocked=!!saved.blocked;this.nextNavigationAt=saved.nextNavigationAt||0;}catch{}}
 persist(){fs.writeFileSync(this.stateFile,JSON.stringify({metrics:this.metrics,blocked:this.blocked,nextNavigationAt:this.nextNavigationAt}));}
 async page({visible=false}={}){if(this.context&&visible&&!this.visibleContext)await this.context.close();if(!this.context){const dir=process.env.GQ_GWDANG_PROFILE||path.join(this.root,'profiles','gwdang');this.context=await (this.launchContext?this.launchContext(dir,{headless:!visible}):chromium.launchPersistentContext(dir,{channel:'msedge',headless:!visible,viewport:{width:1440,height:1000},acceptDownloads:false}));this.visibleContext=visible;this.context.on('close',()=>{this.context=null;this.currentPage=null;this.visibleContext=false;});}if(!this.currentPage||this.currentPage.isClosed())this.currentPage=this.context.pages().find(p=>!p.isClosed())||await this.context.newPage();return this.currentPage;}
 async state(page){const text=(await page.locator('body').innerText({timeout:4000}).catch(()=>'')).slice(0,15000);if(/\/slider\/verify|\/user\/login/.test(page.url())||/访问行为异常|请验证后访问|请完成验证|滑动验证|访问过于频繁/.test(text))return 'verification_required';return null;}
 status(){return {state:this.blocked?'verification_required':this.busy?'running':'idle',metrics:this.metrics,last:this.last&&{sourceUrl:this.last.sourceUrl,collectedAt:this.last.collectedAt,count:this.last.items.length}};}
 async open(){if(this.busy)throw Error('正在后台查询，请等待结束后再打开窗口');const p=await this.page({visible:true});if(p.url()==='about:blank')await p.goto(HOME,{waitUntil:'domcontentloaded',timeout:20000});await p.bringToFront();return {state:'window_open',message:'购物党窗口已打开。若提示验证请先完成，再打开目标商品，点击“读取当前页”。'};}
 async read({keyword='',url='',current=false}={}){
  if(this.busy)throw Error('已有一个采集任务进行中，请等待');if(this.blocked&&!current)return {state:'verification_required',message:'此前出现验证，已暂停新的搜索。完成后请读取当前页。',items:[],metrics:this.metrics};
  const requestedKeyword=keyword.trim()||(current?this.pendingKeyword:'')||(url?queryFromUrl(url):'');if(keyword.trim())this.pendingKeyword=keyword.trim();const plan=searchPlan(requestedKeyword);let target=url?allowedAggregateUrl(url):searchUrl(plan.effective);if(!current&&!target)throw Error('只支持购物党搜索页或商品详情页');if(!current&&!url&&!keyword.trim())throw Error('请填写检索词');
  const key=createHash('sha256').update('gbk-v4:'+target).digest('hex'),file=path.join(this.cacheDir,key+'.json');if(!current&&fs.existsSync(file)){const cached=JSON.parse(fs.readFileSync(file,'utf8'));if(cached.nextPageUrl!==undefined&&this.clock()-Date.parse(cached.collectedAt)<300000){this.metrics.cacheHits++;this.persist();const filtered=filterCandidates(cached.items,requestedKeyword);return {...cached,...filtered,platformCoverage:platformCoverage(cached.items,filtered.items,filtered.excluded),state:filtered.items.length?'collected':'no_match',keyword:requestedKeyword,effectiveKeyword:plan.effective,cached:true,message:'使用5分钟内已保存的候选；来源价格时效仍须核验。',metrics:this.metrics};}}
  if(!current&&this.clock()<this.nextNavigationAt)throw Error('请稍后再查询；两次新页面访问至少间隔30秒。这不是平台保证的安全频率。');
  this.busy=true;this.metrics.startedAt=new Date(this.clock()).toISOString();try{if(!current&&this.context&&this.visibleContext&&!this.keepVisible)await this.context.close();const p=await this.page();if(!current){this.nextNavigationAt=this.clock()+30000;this.metrics.requests++;try{await p.goto(target,{waitUntil:'domcontentloaded',timeout:20000});}catch(e){if(e.name!=='TimeoutError'||p.url()!==target)throw e;}}if(await this.state(p)){if(!this.blocked)this.metrics.verificationEvents++;this.blocked=true;return {state:'verification_required',message:'购物党要求人工验证，已停止请求；已有数据保留。',items:[],metrics:this.metrics};}if(this.blocked){this.metrics.manualResumes++;this.blocked=false;}
  if(!allowedAggregateUrl(p.url()))return {state:'page_changed',message:'当前不是购物党商品页或搜索页，请在窗口中打开目标商品后读取。',items:[]};
  await p.locator('a[href^="/crc64/dp"],a[href*="/product/get_trans?"]').first().waitFor({state:'visible',timeout:8000}).catch(()=>{});if(await this.state(p)){this.blocked=true;this.metrics.verificationEvents++;return {state:'verification_required',message:'页面要求验证，已暂停。',items:[]};}
  const nextPageUrl=validNextPage(await p.evaluate(extractNextPage),p.url());const rows=await p.evaluate(extractAggregate),at=new Date(this.clock()).toISOString(),rawItems=aggregateQuotes(rows,at),query=requestedKeyword||queryFromUrl(p.url()),filtered=filterCandidates(rawItems,query),items=filtered.items;const result={state:items.length?'collected':rawItems.length?'no_match':'page_changed',message:items.length?`取得${items.length}条相关候选，已排除${filtered.excludedCount}条不符商品；选中SKU和价格待核验。`:rawItems.length?'没有找到符合检索条件的商品；已剔除无关推荐和冲突规格。':'页面没有解析到商品，可能未加载完成。',sourceUrl:p.url(),collectedAt:at,keyword:query,effectiveKeyword:plan.effective,rawCount:rawItems.length,excludedCount:filtered.excludedCount,nextPageUrl,filterVersion:3,excluded:filtered.excluded,platformCoverage:platformCoverage(rawItems,items,filtered.excluded),items};this.last=result;if(!current)fs.writeFileSync(file,JSON.stringify({...result,items:rawItems}));return {...result,metrics:this.metrics};
  }finally{this.busy=false;this.metrics.endedAt=new Date(this.clock()).toISOString();this.persist();}}
 async evidence(id){if(this.busy)throw Error('采集进行中，请等待');const item=this.last?.items.find(q=>q.id===id);if(!item)throw Error('候选已过期，请读取当前页后再保存截图');this.busy=true;try{const p=await this.page();if(p.url()!==this.last.sourceUrl||await this.state(p))throw Error('页面已变化或要求验证，请先读取当前页');const card=p.locator(`[data-gq-aggregate="${item.aggregateIndex}"]`);const text=await card.innerText();if(!text.includes(item.title)||text.slice(0,2500)!==item.sourceText)throw Error('商品或价格发生变化，请重新读取');const urls=await card.locator('a[href]').evaluateAll(links=>links.map(a=>a.href));if(!urls.includes(item.url))throw Error('截图卡片链接与报价不一致，已停止保存');const proof=await this.saveImage(await card.screenshot(),item.platform+'-'+item.store+'-聚合截图.png');return {...item,evidence:[{...proof,kind:'aggregate',quoteId:item.id,platform:item.platform,productId:item.aggregateProductId,productUrl:item.url,productTitle:item.title,capturedAt:new Date(this.clock()).toISOString()}]};}finally{this.busy=false;}}
 async snapshot(sourceUrl){if(this.busy)throw Error('采集进行中');this.busy=true;try{const p=await this.page();if(p.url()!==sourceUrl||await this.state(p))throw Error('页面已变化或要求验证');const capturedAt=new Date(this.clock()).toISOString();const proof=await this.saveImage(await p.screenshot({fullPage:false,timeout:8000}),'购物党候选页面.png');return {...proof,kind:'aggregate',sourceUrl,capturedAt};}finally{this.busy=false;}}
 async close(){this.persist();if(this.context)await this.context.close();}
}
