import ExcelJS from 'exceljs';
import {selectedBatchQuotes} from './excel-batch.mjs';
import {quoteEvidence} from '../public/quote-evidence.js';
import fs from 'node:fs';
import path from 'node:path';
import {searchPlan} from './search-match.mjs';

const columns = ['A','B','C','D','E','F','G','H','I','J','K'];
const widths = [7,18,42,9,9,12,13,21,27,16,16];
const safeText = value => { const text=String(value??''); return /^[=+@-]/.test(text) ? "'"+text : text; };
const validUrl = value => /^https:\/\//.test(value||'') ? value : '';
const imageData = (root,id) => {
  if (!/^[a-f0-9-]{36}$/.test(id||'')) return null;
  const file=path.join(root,'files',id); if (!fs.existsSync(file)||!fs.existsSync(file+'.json')) return null;
  try { const meta=JSON.parse(fs.readFileSync(file+'.json','utf8')),mime=meta.mime||'image/png'; if (!['image/png','image/jpeg','image/jpg'].includes(mime)) return null; return {buffer:fs.readFileSync(file),extension:mime==='image/png'?'png':'jpeg'}; } catch { return null; }
};
const stamp = value => new Date(value).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai',hour12:false});
function styleSheet(sheet,maxRow,maxCol=11){ sheet.views=[{showGridLines:false}]; for(let i=1;i<=maxCol;i++) sheet.getColumn(i).width=widths[i-1]||20; for(let r=1;r<=maxRow;r++){sheet.getRow(r).font={name:'Microsoft YaHei',size:10,color:{argb:'FF111111'}};sheet.getRow(r).alignment={vertical:'middle',wrapText:true};} }
function borderRows(sheet,startRow,endRow,startCol,endCol){for(let r=startRow;r<=endRow;r++)for(let c=startCol;c<=endCol;c++)sheet.getCell(r,c).border={top:{style:'thin',color:{argb:'FF333333'}},left:{style:'thin',color:{argb:'FF333333'}},bottom:{style:'thin',color:{argb:'FF333333'}},right:{style:'thin',color:{argb:'FF333333'}}};}
function addImage(workbook,sheet,image,row,col,width,height){const id=workbook.addImage({buffer:image.buffer,extension:image.extension});sheet.addImage(id,{tl:{col,row},ext:{width,height}});}

export async function exportDemoXlsx({result,root,output,options={},previewDir,batch}){
 if(batch){const items=batch.groups.flatMap((group,index)=>{const chosen=selectedBatchQuotes(group),rows=[...chosen];while(rows.length<3)rows.push({id:`missing-${group.id}-${rows.length}`,platform:`平台缺项${rows.length+1}`,title:group.message||'尚未执行搜索',price:null,url:'',evidence:[]});return rows.map(q=>({...q,batchDemand:{...group,result:undefined,index:index+1}}));});result={items,keyword:batch.fileName,collectedAt:batch.createdAt};}
 if(!result||!Array.isArray(result.items))throw Error('没有可导出的报价结果');
 const title=safeText(options.title||(batch?'商品三方比价汇总（待核验）':'商品报价单（平台比价测试）')),quantity=options.quantity===''||options.quantity==null?null:Number(options.quantity);
 if(quantity!==null&&(!Number.isFinite(quantity)||quantity<=0||quantity>1e9))throw Error('报价数量须大于0');
 const items=result.items.filter(q=>!options.ids||options.ids.includes(q.id)); if(!items.length)throw Error('请先选择需要导出的相关商品'); if(!batch&&new Set(items.map(q=>q.platform)).size!==items.length)throw Error('最终报价单每个平台最多选择一条，请调整勾选'); if(items.length>(batch?600:40))throw Error('导出条目超过上限');
 const fields=result.input?.fields||searchPlan(result.keyword||'').fields,workbook=new ExcelJS.Workbook(); workbook.creator='贵昌报价工具'; workbook.created=new Date();
 const sheet=workbook.addWorksheet('报价单'),proof=workbook.addWorksheet('截图凭证'); styleSheet(sheet,items.length+6); styleSheet(proof,Math.max(80,items.length+8),8); const end=items.length+2;
 sheet.mergeCells('A1:K1');sheet.getCell('A1').value=title;sheet.getCell('A1').font={name:'Microsoft YaHei',size:17,bold:true};sheet.getCell('A1').alignment={horizontal:'center',vertical:'middle'};sheet.getRow(1).height=40;
 sheet.getRow(2).values=['序号','物品名称','需求参数/型号','单位','数量','单价','总价','图片','厂家','链接','需求科室'];sheet.getRow(2).font={name:'Microsoft YaHei',size:10,bold:true};sheet.getRow(2).alignment={horizontal:'center',vertical:'middle',wrapText:true};sheet.getRow(2).height=32;
 const name=safeText([fields.brand,fields.name||fields.model].filter(Boolean).join(' ')||result.keyword),unit=safeText(options.unit||'待确认'),dept=safeText(options.department||'待填写');
 items.forEach((q,i)=>{const row=i+3,d=q.batchDemand,source=validUrl(q.originUrl||q.url),evidence=quoteEvidence(q);sheet.getRow(row).values=[d?(i%3===0?d.index:null):(i===0?1:null),d?safeText([d.brand,d.name].filter(Boolean).join(' ')):name,safeText((d?'需求：'+(d.spec||'规格待补充')+'\n':'')+(q.title||'')+'\n'+(q.matchNotes||'选中SKU及售卖包装待核验')),d?safeText(d.unit||'待确认'):unit,d?d.quantity:quantity,typeof q.price==='number'?q.price:null,null,evidence?'':'该报价未取得截图',safeText(q.platform+(q.store?'\n'+q.store:'')),source?{text:'打开商品',hyperlink:source,tooltip:source}:'无链接',d?(i%3===0?safeText(d.department||'待填写'):null):(i===0?dept:null)];sheet.getRow(row).height=evidence?190:116;for(const c of ['E','F','G'])sheet.getCell(`${c}${row}`).numFmt=c==='E'?'0.##':'#,##0.00';if(!batch){const computed=quantity!==null&&typeof q.price==='number'?Math.round(quantity*q.price*100)/100:'';sheet.getCell(`G${row}`).value={formula:`IF(OR(E${row}=\"\",F${row}=\"\"),\"\",ROUND(E${row}*F${row},2))`,result:computed};}for(const c of ['D','E'])sheet.getCell(`${c}${row}`).fill={type:'pattern',pattern:'solid',fgColor:{argb:'FFFFF4CC'}};if(evidence){const image=imageData(root,evidence.id);if(image)addImage(workbook,sheet,image,row-1,7,140,116);}});
 borderRows(sheet,2,end,1,11); for(const c of ['D','E','F','G'])sheet.getColumn(c).alignment={horizontal:'right',vertical:'middle',wrapText:true}; if(batch)for(let i=0;i<items.length;i+=3)for(const col of ['A','K'])sheet.mergeCells(`${col}${i+3}:${col}${Math.min(i+5,end)}`);else if(end>3)for(const col of ['A','K'])sheet.mergeCells(`${col}3:${col}${end}`);for(let r=end+1;r<=end+3;r++){sheet.mergeCells(`A${r}:K${r}`);sheet.getRow(r).height=38;}
 sheet.getCell(`A${end+1}`).value=`报价人：${safeText(options.person||'待填写')}     联系电话：${safeText(options.phone||'待填写')}     报价单位：${safeText(options.company||'待填写')}     ${batch?'批次开始时间':'采集时间'}：${stamp(result.collectedAt)}`;sheet.getCell(`A${end+2}`).value=batch?'数量与单位为客户需求，单价按来源页面售卖包装计，尚未确认单位换算，因此总价留空。每个平台最多一条候选，选中SKU仍待核验。':'说明：厂家栏沿用样表填写平台/店铺。单价为对应来源页面展示价，按页面售卖包装计；黄色格为数量及单位输入。尚未核验选中SKU、库存、税费和运费。';sheet.getCell(`A${end+3}`).value='各行是同一需求的不同候选报价，不累计为采购总额。截图凭证页保留来源与待核验事项；缺失的平台不补造报价。';sheet.views=[{state:'frozen',ySplit:2,showGridLines:false}];
 proof.mergeCells('A1:H1');proof.getCell('A1').value='采集来源及截图';proof.getCell('A1').font={name:'Microsoft YaHei',size:15,bold:true};proof.getCell('A1').alignment={horizontal:'center',vertical:'middle'};proof.getRow(1).height=32;proof.mergeCells('A2:H2');proof.getCell('A2').value=`需求：${safeText(result.keyword)}。读取时间：${stamp(result.collectedAt)}。截图来源按各图标注，搜索页截图不代表已核验商品详情或成交条件。`;proof.getRow(2).height=36;proof.getRow(3).values=['报价行','平台/店铺','商品来源','核验状态'];proof.getRow(3).font={name:'Microsoft YaHei',size:10,bold:true};
 items.forEach((q,i)=>{const row=i+4,url=validUrl(q.url);proof.getRow(row).values=[i+3,safeText(q.platform+' '+(q.store||'')),url?{text:safeText(q.url),hyperlink:url,tooltip:url}:safeText(q.url),safeText((q.matchNotes||'待核验')+'\n读取时间：'+(q.collectedAt||q.checkedAt||'未知'))];proof.getRow(row).height=52;});proof.getColumn(2).width=35;proof.getColumn(3).width=35;proof.getColumn(4).width=35;borderRows(proof,3,items.length+3,1,4);let imageRow=items.length+5;
 for(const [i,q] of items.entries()){const evidence=quoteEvidence(q),image=evidence&&imageData(root,evidence.id);if(!image)continue;proof.mergeCells(`A${imageRow}:H${imageRow}`);proof.getCell(`A${imageRow}`).value=`报价单第${i+3}行：${safeText(q.platform)}，商品卡片截图（${q.sourceKind==='search'?'原商城搜索页，SKU待核验':'购物党聚合页，原商城凭证待补充'}）`;proof.getRow(imageRow).height=22;addImage(workbook,proof,image,imageRow,0,350,220);imageRow+=15;}if(imageRow===items.length+5){proof.mergeCells(`A${imageRow}:H${imageRow}`);proof.getCell(`A${imageRow}`).value='所选报价尚无逐商品截图，需补充；需求原图不能替代报价凭证';}proof.views=[{showGridLines:false}];
 if(batch){const input=workbook.addWorksheet('需求清单');styleSheet(input,batch.rows.length+1,10);input.views=[{state:'frozen',ySplit:1,showGridLines:false}];input.getRow(1).values=['来源工作表','Excel行号','原行号','商品名称','品牌','规格型号','需求数量','需求单位','需求科室','搜索词'];input.getRow(1).font={name:'Microsoft YaHei',size:10,bold:true};batch.rows.forEach((r,i)=>{input.getRow(i+2).values=[safeText(r.sheet),r.excelRow,safeText(r.sourceRow),safeText(r.name),safeText(r.brand),safeText(r.spec),r.quantity,safeText(r.unit),safeText(r.department),safeText(r.query)];input.getRow(i+2).height=50;});borderRows(input,1,batch.rows.length+1,1,10);}
 if(previewDir){fs.mkdirSync(previewDir,{recursive:true});fs.writeFileSync(path.join(previewDir,'README.txt'),'便携 ExcelJS 导出不生成工作表 PNG 预览；previewDir 仅保留此说明。Excel 内嵌截图与截图凭证页仍会生成。\n','utf8');}fs.mkdirSync(path.dirname(output),{recursive:true});await workbook.xlsx.writeFile(output);return {count:items.length,output};
}
