const $=id=>document.getElementById(id);
const fields={salesOrgId:'销售组织ID',transactionTypeId:'交易类型ID',agentId:'客户ID',settlementOrgId:'开票组织ID',invoiceAgentId:'开票客户ID',currencyId:'币种ID',natCurrencyId:'本币ID',exchangeRateType:'汇率类型ID',stockOrgId:'库存组织ID',saleDepartmentId:'销售部门ID',corpContact:'销售业务员ID',vouchdate:'单据日期',hopeReceiveDate:'希望到货日期'};
let rows=[],mode='live',plan=null,status={};
async function api(path,data,raw=false){const res=await fetch(path,{method:'POST',headers:{'Content-Type':raw?'application/octet-stream':'application/json'},body:raw?data:JSON.stringify(data)});const out=await res.json();if(!res.ok)throw Error(out.error||'处理失败');return out;}
function invalidate(){plan=null;$('save').disabled=true;$('payload').textContent='内容已变化，请重新检查';$('result').textContent='';$('errors').replaceChildren();}
for(const [key,label] of Object.entries(fields)){const l=document.createElement('label');l.textContent=label;const input=document.createElement('input');input.id=key;input.type=key.endsWith('date')||key==='hopeReceiveDate'?'date':'text';input.addEventListener('input',invalidate);l.append(input);$('headerFields').append(l);}
$('reviewed').onchange=invalidate;$('receiveAddress').oninput=invalidate;
function header(){return {...Object.fromEntries(Object.keys(fields).map(k=>[k,$(k).value.trim()])),receiveAddress:$('receiveAddress').value.trim(),reviewed:$('reviewed').checked};}
function inputCell(td,row,key,label){const input=document.createElement('input');input.value=row[key]??'';input.setAttribute('aria-label',label);input.oninput=()=>{row[key]=input.value;invalidate();};td.append(input);return input;}
function render(){
 $('rows').replaceChildren();
 rows.forEach((row,i)=>{const tr=document.createElement('tr');const cells=Array.from({length:7},()=>{const td=document.createElement('td');tr.append(td);return td;});
 inputCell(cells[0],row,'name','商品名称');const note=document.createElement('small');note.textContent=[row.spec,row.deliveryLocation&&`原科室备注：${row.deliveryLocation}`,row.sourcePrice&&`原图参考价：${row.sourcePrice}`,row.sourceCode&&`表格原编码：${row.sourceCode}`].filter(Boolean).join('；');cells[0].append(note);
 inputCell(cells[1],row,'quantity','数量');const u=document.createElement('small');u.textContent=row.unit||'原表无单位，待确认';cells[1].append(u);
 inputCell(cells[2],row,'productId','用友商品ID');inputCell(cells[3],row,'unitId','同一单位ID');inputCell(cells[4],row,'taxId','税目ID');inputCell(cells[4],row,'taxRate','税率（如0.13）').placeholder='税率小数，不能猜测';
 inputCell(cells[5],row,'price','含税单价');inputCell(cells[5],row,'priceSource','价格依据').placeholder='合同价/人工确认报价/系统价';
 const label=document.createElement('label');const cb=document.createElement('input');cb.type='checkbox';cb.checked=row.sameUnitConfirmed===true;cb.onchange=()=>{row.sameUnitConfirmed=cb.checked;invalidate();};label.append(cb,document.createTextNode('三个单位相同'));cells[6].append(label);
 for(const [text,path] of [['查商品','products'],['查系统价格','price']]){const b=document.createElement('button');b.textContent=text;b.onclick=async()=>{b.disabled=true;try{if(mode==='mock')throw Error('当前是模拟样例，未调用用友；上传实际表格进入真实预览。');$('lookup').textContent='正在查询…';const out=await api('/api/'+path,path==='products'?{name:row.name}:{header:header(),row});$('lookup').textContent=JSON.stringify(out,null,2);$('lookup').parentElement.open=true;}catch(e){$('lookup').textContent=e.message;$('lookup').parentElement.open=true;}finally{b.disabled=false;}};cells[6].append(b);}
 $('rows').append(tr);});
 $('mode').textContent=mode==='mock'?'模拟测试：编码、价格、客户均为虚拟，不会发往用友。':'真实表格预览：查询需要应用凭证，保存默认锁定。';invalidate();
}
$('file').onchange=async e=>{const file=e.target.files[0];if(!file)return;invalidate();rows=[];mode='live';for(const k of Object.keys(fields))if($(k).value.startsWith('DEMO-'))$(k).value='';$('reviewed').checked=false;render();try{if(!file.name.toLowerCase().endsWith('.xlsx'))throw Error('请选择XLSX文件');const out=await api('/api/xlsx',await file.arrayBuffer(),true);rows=out.rows;$('source').textContent=`${file.name} · ${out.sheet} · ${rows.length}行`;render();}catch(err){$('source').textContent='文件未载入，不能继续保存';$('result').textContent=err.message;}};
$('demo').onclick=async()=>{try{const out=await api('/api/demo',{});rows=out.rows;mode=out.mode;for(const k of Object.keys(fields))$(k).value=out.header[k]||'';$('reviewed').checked=false;$('receiveAddress').value='';$('source').textContent='虚拟样例 · 1行 · 4箱模拟复印纸';render();}catch(e){$('result').textContent=e.message;}};
$('preview').onclick=async()=>{invalidate();$('preview').disabled=true;try{plan=await api('/api/preview',{rows,header:header(),mode});$('errors').replaceChildren();for(const error of plan.errors){const li=document.createElement('li');li.textContent=error;$('errors').append(li);}$('payload').textContent=plan.payload?JSON.stringify(plan.payload,null,2):'必填字段未齐，未生成可发送请求。';$('result').textContent=plan.ready?`预览就绪：${plan.rowCount}行，含税合计${plan.total}。尚未保存。`:`还有${plan.errors.length}项待处理，未写入用友。`;$('save').textContent=mode==='mock'?'模拟保存（不连接用友）':'保存到用友（不提交、不审核）';$('save').disabled=!plan.ready||(mode==='live'&&(!status.configured||!status.liveSaveEnabled));}catch(e){$('result').textContent=e.message;}finally{$('preview').disabled=false;}};
$('save').onclick=async()=>{if(!plan)return;const active=plan;$('save').disabled=true;if(!confirm(mode==='mock'?'运行一次本机模拟保存？不会连接用友。':`确认向用友保存本次订单？${active.rowCount}行，合计${active.total}。不提交、不审核。`)){return;}try{const out=await api('/api/save',{planId:active.planId,confirmation:'确认仅保存，不提交不审核'});$('result').textContent=out.message+(out.code?` 单号：${out.code}`:'')+(out.state==='uncertain'?' 请勿重试。':'');}catch(e){$('result').textContent=e.message;}};
fetch('/api/status').then(r=>r.json()).then(s=>{status=s;$('connection').textContent=s.configured?'已检测到本机应用凭证（不代表连通已验证）。真实保存'+(s.liveSaveEnabled?'已显式开启。':'仍锁定。'):'尚未配置本机用友应用凭证。可以先做表格预览和模拟测试，不能真实导入。';}).catch(()=>{$('connection').textContent='本机导入服务未连接。';});
// An optional read-only agent surface; no hidden submit/save tools.
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'read_order_import_preview',description:'读取当前可见订单预览状态，不调用用友、不写入。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true,untrustedContentHint:true},execute:()=>({mode,rowCount:rows.length,ready:plan?.ready??false,errors:plan?.errors??[],total:plan?.total??null})})).catch(()=>{});}catch{}}
