const text=v=>String(v??'');
async function api(path,data,extra={}) { const r=await fetch(path,{method:data===undefined?'GET':'POST',headers:{'Content-Type':'application/json',...extra},body:data===undefined?undefined:JSON.stringify(data)}); const j=await r.json();if(!r.ok||j.error)throw Error(j.error||'处理失败');return j; }
const pricing=(action,data={})=>api('/api/workflow/order-pricing/'+action,data);
export function OrderTools({React,batch,draft,disabled,onSave,onApply}) {
 const [busy,setBusy]=React.useState(false),[message,setMessage]=React.useState(''),[session,setSession]=React.useState(null),[projects,setProjects]=React.useState({}),[projectId,setProjectId]=React.useState(''),[date,setDate]=React.useState(''),[results,setResults]=React.useState({}),[line,setLine]=React.useState(''),[factor,setFactor]=React.useState('1'),[mappings,setMappings]=React.useState(null);
 const current=React.useRef(draft);current.current=draft;const row=draft.rows.find(r=>r.sourceLineId===line)||draft.rows[0];const expected=JSON.stringify(draft);
 const [rule,setRule]=React.useState({name:'',purpose:'sales',basis:'average_price',adjustment_kind:'rate',adjustment:'0',fee:'0',fee_order:'before',rounding:'ROUND',fixed_price:'0'});
 async function run(fn){if(busy||disabled)return;setBusy(true);setMessage('');try{await fn();}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 function apply(next,key=expected){if(JSON.stringify(current.current)!==key)throw Error('订单已修改，旧结果未应用；请保存后重试');onApply(next,key);setSession(null);setResults({});setMappings(null);}
 async function saved(){if(!await onSave())throw Error('保存期间有新修改，请重新保存');return api('/api/workflow/batches/'+batch.batchId);}
 async function start(){const record=await saved();const s=await pricing('start',{batchId:batch.batchId,draftHash:record.draftHash,projectId,date});setSession({...s,expected});setResults({});setMessage(`本单 ${s.rowCount} 行已接入查价，无需重新上传。`);}
 async function query(){const result=await pricing('query',{id:session.id,sourceLineId:row.sourceLineId});setResults(v=>({...v,[row.sourceLineId]:result}));}
 async function adoptSource(){if(!row||!text(row.sourcePrice).trim())throw Error('本行没有原单价格');if(!row.unit||row.unit!==row.sourceDemandUnit)throw Error('原单与当前单位不同，请先核对换算');const rows=draft.rows.map(r=>r===row?{...r,price:text(r.sourcePrice),priceSource:'人工核对原单价格',priceNeedsReview:false}:r);apply({...draft,header:{...draft.header,reviewed:false},rows});setMessage('已带入原单价格；请核对本次商品后保存底稿。');}
 async function quote(){await saved();const s=await api('/api/session');const headers={'X-Quote-Owner':s.user.id,'X-CSRF-Token':s.csrf};const q=await api('/api/quote/workflow',undefined,headers);
 const rows=batch.snapshot.rows.map((r,i)=>({sourceRowId:text(r.id||i+1),originalName:text(r.name),spec:text(r.spec),quantity:r.quantity,unit:text(r.unit),originalRow:r}));
 const payload={sourceDocumentId:batch.parentBatchId||batch.batchId,sourceLabel:batch.customerOriginal?.filename||draft.rows[0]?.sourceFile||'本单原始需求',rows};const frame=document.querySelector('#gc-quote-panel iframe');const importer=frame?.contentWindow?.GCQuoteImportRows;const result=importer?await importer(payload):await api('/api/quote/workflow/import',{revision:q.revision,...payload},headers);setMessage(`本单 ${rows.length} 个原行已接到三方报价，报价工作区共 ${result.rows.length} 行；同一原行再次发送不会新增。`);}
 const result=results[row?.sourceLineId];const ready=Object.keys(results).filter(id=>results[id].confirmed);
 return <section className="flow-card" aria-label="本单连续处理"><h2>本单查价、底稿与报价衔接</h2><p>沿用当前 {draft.rows.length} 个原行。参考价保留日期、规则和来源，最终成交仍需核对。</p><div className="flow-actions">
 <button disabled={disabled||busy} onClick={()=>run(async()=>{await saved();const a=document.createElement('a');a.href=`/api/workflow/batches/${batch.batchId}/files/draft.xlsx`;a.download='';a.click();setMessage('当前底稿已生成，包含原行、价格和映射。');})}>保存并下载当前底稿</button>
 <button disabled={disabled||busy} onClick={()=>run(quote)}>本单原行送三方报价</button><button disabled={busy} onClick={()=>document.getElementById('gc-quote-tab')?.click()}>查看三方报价</button></div>
 <label>当前商品<select aria-label="衔接商品行" value={row?.sourceLineId||''} onChange={e=>{setLine(e.target.value);setMappings(null);}}>{draft.rows.map((r,i)=><option key={r.sourceLineId} value={r.sourceLineId}>{i+1}. {r.name} · {r.unit}</option>)}</select></label>
 <div className="flow-actions"><button disabled={disabled||busy||!text(row?.sourcePrice).trim()} onClick={()=>run(adoptSource)}>核对后采用原单价格 {row?.sourcePrice}</button><button disabled={disabled||busy} onClick={()=>run(async()=>{const r=await api('/api/workflow/mappings/lookup',{header:draft.header,row});setMappings({...r,key:expected});})}>查找已确认底稿映射</button></div>
 {mappings?.key===expected&&<div><p>{mappings.message}</p>{!mappings.candidates.length&&<p>没有符合条件的已确认映射。</p>}{mappings.candidates.map((c,i)=><p key={i}>{c.row.name} · {c.row.code} · {c.row.unit} <a href={c.downloadUrl}>原确认底稿</a> <button disabled={busy||disabled} onClick={()=>run(async()=>{const r=await api('/api/workflow/mappings/apply',{header:draft.header,row,mappingBatchId:c.batchId,mappingLineId:c.sourceLineId});apply({...draft,header:{...draft.header,reviewed:false},rows:draft.rows.map(x=>x===row?r.row:x)});})}>核对后复用</button></p>)}</div>}
 <details><summary>本单查询参考价格</summary><div className="flow-actions"><button disabled={busy||disabled} onClick={()=>run(async()=>setProjects(await pricing('projects')))}>读取已保存项目规则</button><select aria-label="本单价格规则" value={projectId} onChange={e=>{setProjectId(e.target.value);setSession(null);setResults({});}}><option value="">选择已确认规则</option>{Object.values(projects).map(r=><option key={r.id} value={r.id}>{r.name} · v{r.version}</option>)}</select><input aria-label="行情日期" type="date" value={date} onChange={e=>{setDate(e.target.value);setSession(null);setResults({});}}/><button disabled={disabled||busy} onClick={()=>run(start)}>保存本单并开始查价</button></div>
 <details><summary>维护项目规则</summary><p>请按实际项目约定填写；下浮5%填 -0.05，系数95%填 0.95。</p><div className="flow-grid">{[['name','项目名称'],['fee','加工费'],['adjustment','浮动值或系数'],['fixed_price','固定价']].map(([key,label])=><label key={key}>{label}<input aria-label={label} value={rule[key]} onChange={e=>setRule({...rule,[key]:e.target.value})}/></label>)}{[['purpose','用途',[['sales','销售参考'],['purchase','采购参考']]],['basis','基准',[['average_price','平均价'],['low_price','最低价'],['high_price','最高价'],['fixed','固定价']]],['adjustment_kind','浮动口径',[['rate','增减率'],['coefficient','乘数']]],['fee_order','加工费顺序',[['before','先加费用再浮动'],['after','先浮动再加费用']]],['rounding','取整',[['ROUND','四舍五入两位'],['ROUNDDOWN','截取两位'],['none','不取整']]]].map(([key,label,choices])=><label key={key}>{label}<select aria-label={label} value={rule[key]} onChange={e=>setRule({...rule,[key]:e.target.value})}>{choices.map(([id,name])=><option key={id} value={id}>{name}</option>)}</select></label>)}</div><button disabled={busy||disabled} onClick={()=>run(async()=>{const r=await pricing('projects',{project:rule});setProjects(await pricing('projects'));setProjectId(r.id);setSession(null);setMessage('已保存项目规则，请核实适用日期和用途。');})}>保存规则</button></details>
 {session&&<div><p>本次接入 {session.rowCount} 行，已确认 {ready.length} 行。</p><button disabled={busy||disabled||session.expected!==expected} onClick={()=>run(query)}>查询当前商品</button>{session.expected!==expected&&<p>订单已变化，请保存并重新开始查价。</p>}{result&&<div><p>{result.status}</p><label>1 当前单位对应多少行情单位<input aria-label="行情单位换算比例" value={factor} onChange={e=>setFactor(e.target.value)}/></label>{(result.items||[]).map((item,i)=><p key={i}>{item.name} · {item.spec} · {item.origin} · {item.unit} · {item.average_price} · {item.published_at} <a href={item.reference_url} target="_blank" rel="noreferrer">原来源</a> <button disabled={busy||disabled} onClick={()=>run(async()=>{const r=await pricing('confirm',{id:session.id,sourceLineId:row.sourceLineId,index:i,factor});setResults(v=>({...v,[row.sourceLineId]:r}));})}>确认此候选与换算</button></p>)}</div>}<button disabled={busy||disabled||session.expected!==expected} onClick={()=>run(async()=>{const r=await pricing('apply',{id:session.id,sourceLineIds:ready});apply(r.draft,session.expected);setMessage(`已带回 ${r.appliedCount}/${r.totalCount} 行参考价，其余原行与原价完整保留，待核 ${r.counts.pending} 行；请复核并保存底稿。`);})}>整单带回参考价与待核状态</button></div>}</details>
 {message&&<p role="status">{message}</p>}</section>;
}
export function InvoiceMappingTools({React,draft,onChange,disabled}) {
 const [result,setResult]=React.useState(null),[message,setMessage]=React.useState(''),[busy,setBusy]=React.useState(false);const latest=React.useRef(draft);latest.current=draft;const key=JSON.stringify(draft);
 const header={...draft.header,knowledgeBaseId:draft.header.knowledgeBaseId||'default-catalog',agentId:draft.header.customerId,invoiceAgentId:draft.header.customerId};
 async function lookup(){setBusy(true);setMessage('');try{const found=[];for(let i=0;i<draft.rows.length;i++){const row=draft.rows[i];if(row.code)continue;const r=await api('/api/workflow/mappings/lookup',{header,row:{originalCode:row.sourceCode,sourceName:row.name,sourceSpec:row.spec,sourceDemandUnit:row.unit}});found.push({index:i,...r});}if(JSON.stringify(latest.current)===key)setResult({key,found});}catch(e){setMessage(e.message);}finally{setBusy(false);}}
 function apply(index,c){if(JSON.stringify(latest.current)!==key){setMessage('开票清单已变化，请重新查询');return;}if(c.row.unit!==draft.rows[index].unit){setMessage('底稿用友单位与本次开票单位不同，请先确认换算；未改数量或价格');return;}
 onChange({...draft,rows:draft.rows.map((r,i)=>i===index?{...r,code:c.row.code,mappingReference:{batchId:c.batchId,sourceLineId:c.sourceLineId,planId:c.planId}}:r)});setResult(null);setMessage('已复用用友编码，开票数量、价格和税率保留；下推前仍按原流程校验。');}
 return <div className="invoice-actions"><button disabled={busy||disabled} onClick={lookup}>从已确认录单底稿匹配开票编码</button>{message&&<p role="status">{message}</p>}{result?.key===key&&result.found.map(r=><div key={r.index}>第{r.index+1}行：{!r.candidates.length?'没有精确匹配':r.candidates.map((c,i)=><span key={i}>{c.row.code} · {c.row.name} <button disabled={busy||disabled} onClick={()=>apply(r.index,c)}>核对后采用此编码</button></span>)}</div>)}</div>;
}
